### ISSUE TITLE
Sample meta validate input: leading or tailing spaces in file paths are kept in output, error should be raised or remove spaces

### ISSUE THREAD

**Issue by byb121** [cancerit/cgpNgsQc#20]
Sample meta validate input: 
Code is removing leading and tailing spaces when validating file paths, but kept them in the output. Downstream process of the output should be aware of this.

**Comment by keiranmraine** [comment]
@byb121 , can you provide an example causing this to occur.  Unless the file path has been quoted I would expect the shell to remove additional whitespace.

**Comment by byb121** [comment]
The code takes whatever in the input file and dump them into the output, then adds more columns. When calling shell commands, the code removes leading/trailing whitespaces. So validation won't raise an error, but the output will have those whitespaces kept. 

I use python code to take the file paths from the output and subprocess to call shell commands, and it does not tolerate trailing spaces. I think subprocess unfortunately does quote commands. 

I'll fix it next week.
